spring: 
  datasource:
    driver-class-name: org.postgresql.Driver
    platform: postgres    
    url: jdbc:postgresql://${postgres.host}:${postgres.port}/${postgres.database}
    username: ${postgres.username}
    password: ${postgres.password}
  flyway:
    enabled: true
---
management:
  metrics:
    export:
      simple:
        enabled: true
  endpoint:
    health:
      enabled: true
      probes:
        enabled: true
      group:
        readiness:
          include: "*"
          show-details: always
        liveness:
          include:
            - ping
          show-details: never
    info:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
        - metrics
        - health
        - info
        - prometheus
---
spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/lab_db
    username: postgres
    password: postgres
    initialization-mode: always
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.postgresql.Driver
    platform: postgres    
    url: jdbc:postgresql://localhost:5432/lab_db
    username: postgres
    password: postgres
  flyway:
    enabled: true
    baseline-on-migrate: true
    
postgres:
  host: localhost  
  port: 5432
  username: postgres
  password: postgres
  database: lab_db

management:
  endpoints:
    web:
      exposure:
        include: "*"
